server:
  port: 8081

# database 연동 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mariadb://127.0.0.1:3306/member?allowPublicKeyRetrieval=true&useSSL=false
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: findGEO
    password: Abcd123@
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update